/**
 * docs-sync — mirrors per-symbol reference docs from upstream packages into
 * docs/reference/<area>/<name>.mdx, adding an inline source badge and a proxy
 * disclosure at the bottom. Hand-written pages (originals, ts-pattern, prose, concepts) are
 * never touched.
 *
 * Modes:
 *   pnpm docs:sync              # write
 *   pnpm docs:sync:check        # CI — fail on drift, no writes
 *
 * Inputs:
 *   docs/_meta/upstream-versions.json   (pinned tags)
 *   packages/massaman/src/<area>/index.ts (re-export classifications)
 *
 * Outputs:
 *   docs/reference/<area>/<name>.mdx    (proxy pages)
 *   docs/_meta/proxies.json             (manifest)
 */

import 'zx/globals'
import type { Dirent } from 'node:fs'

import { withReferenceDescription } from './descriptions.ts'
import { transformReferenceFields } from './fields.ts'

$.verbose = false

const ROOT = path.resolve(import.meta.dirname, '../../..')
const META_PATH = path.join(ROOT, 'docs', '_meta', 'upstream-versions.json')
const MANIFEST_PATH = path.join(ROOT, 'docs', '_meta', 'proxies.json')
const CACHE_DIR = path.join(ROOT, 'node_modules', '.cache', 'docs-sync')
const SRC_ROOT = path.join(ROOT, 'packages', 'massaman', 'src')
const DOCS_REF = path.join(ROOT, 'docs', 'reference')

type UpstreamPackage = {
  version: string
  repo: string
  siteUrl: string
  siteOrigin: string
  undocumentedUpstream?: Record<string, string>
}

type UpstreamConfig = {
  'es-toolkit': UpstreamPackage
  'ts-pattern': UpstreamPackage
}

type ExportDefinition =
  | { name: string; kind: 'local' }
  | { name: string; kind: 'proxy:ts-pattern' }
  | { name: string; kind: 'proxy:es-toolkit'; upstreamArea: string }

type Classification = ExportDefinition & { massamanArea: string }

type Reference = {
  name: string
  massamanArea: string
}

type ManifestEntry = Classification & {
  status: 'original' | 'hand-written' | 'proxy'
  expectedFile: string
  source?: 'es-toolkit' | 'ts-pattern'
  upstreamUrl?: string
  undocumentedUpstream?: string
}

type ClassificationResult = {
  entry: ManifestEntry | null
  errors: string[]
  wrote: number
  handWritten: number
  local: number
}

export async function syncDocs({ check }: { check: boolean }): Promise<void> {
  const cfg = (await fs.readJson(META_PATH)) as UpstreamConfig
  const es = cfg['es-toolkit']
  const tsp = cfg['ts-pattern']

  console.log(
    chalk.cyan(
      `docs-sync ${check ? '(check)' : ''} — es-toolkit@${es.version}, ts-pattern@${tsp.version}`
    )
  )

  const upstreamDir = await ensureUpstream(es.repo, es.version)

  const classifications = await classifyAllExports()

  const errors: string[] = []

  await migrateHandWrittenFields(errors, check)
  const results = await Promise.all(
    classifications.map((classification) =>
      processClassification(classification, { check, es, tsp, upstreamDir })
    )
  )
  const manifest = results.flatMap(({ entry }) => (entry === null ? [] : [entry]))
  errors.push(...results.flatMap((result) => result.errors))
  const wrote = results.reduce((count, result) => count + result.wrote, 0)
  const proxyHandWritten = results.reduce((count, result) => count + result.handWritten, 0)
  const locals = results.reduce((count, result) => count + result.local, 0)

  // Orphan detection: proxy .md on disk that no longer maps to a re-export.
  // We can't blanket-flag all .md (originals are hand-written), so we scope to
  // "looks like a proxy" — has the canonical callout marker on line 3.
  await detectOrphans(manifest, errors)
  await detectPlaceholderPages(errors)
  await normalizeReferenceDescriptions(errors, check)

  if (!check) {
    await fs.outputJson(
      MANIFEST_PATH,
      {
        $comment: 'Generated by scripts/docs.ts sync — do not edit by hand.',
        generatedAt: new Date().toISOString(),
        versions: { 'es-toolkit': es.version, 'ts-pattern': tsp.version },
        counts: { proxy: wrote, handWrittenProxy: proxyHandWritten, original: locals },
        pages: manifest.toSorted((a, b) =>
          `${a.massamanArea}/${a.name}`.localeCompare(`${b.massamanArea}/${b.name}`)
        ),
      },
      { spaces: 2 }
    )
  }

  // Summary
  console.log(
    chalk.green(`  ${check ? 'verified' : 'wrote'} ${wrote} proxy pages from es-toolkit`)
  )
  console.log(chalk.gray(`  ${proxyHandWritten} proxy pages are hand-written (not generated)`))
  console.log(chalk.gray(`  ${locals} originals expected (hand-written, not touched)`))

  if (errors.length > 0) {
    console.log(chalk.red(`\n✗ ${errors.length} issue(s):`))
    for (const e of errors) console.log(chalk.red(`  - ${e}`))
    process.exit(1)
  }
  console.log(chalk.green('\n✓ ok'))
}

// -----------------------------------------------------------------------------

async function processClassification(
  classification: Classification,
  {
    check,
    es,
    tsp,
    upstreamDir,
  }: {
    check: boolean
    es: UpstreamPackage
    tsp: UpstreamPackage
    upstreamDir: string
  }
): Promise<ClassificationResult> {
  if (classification.kind === 'local') {
    const expectedFile = await existingRef(classification)
    return {
      entry: {
        ...classification,
        status: 'original',
        expectedFile: expectedFile ?? `${refBase(classification)}.mdx`,
      },
      errors:
        expectedFile === null
          ? [`missing local reference page: ${refBase(classification)}`]
          : [],
      wrote: 0,
      handWritten: 0,
      local: 1,
    }
  }

  if (classification.kind === 'proxy:ts-pattern') {
    const expectedFile = await existingRef(classification)
    return {
      entry: {
        ...classification,
        status: 'hand-written',
        source: 'ts-pattern',
        upstreamUrl: tsp.siteUrl,
        expectedFile: expectedFile ?? `${refBase(classification)}.mdx`,
      },
      errors:
        expectedFile === null
          ? [`missing ts-pattern reference page: ${refBase(classification)}`]
          : [],
      wrote: 0,
      handWritten: 1,
      local: 0,
    }
  }

  const upstreamMd = path.join(
    upstreamDir,
    'docs',
    ...upstreamDocSegments(classification.upstreamArea, classification.name)
  )
  if (!(await fs.pathExists(upstreamMd))) {
    return processUndocumentedExport(classification, es)
  }

  const upstreamUrl = upstreamDocUrl(es, classification.upstreamArea, classification.name)
  const original = await fs.readFile(upstreamMd, 'utf8')
  const transformed = withProxyTitle(
    withReferenceDescription(
      decorateProxyPage(
        transformReferenceFields(original).content,
        classification.name,
        upstreamUrl
      )
    ),
    classification.name
  )
  const outPath = path.join(DOCS_REF, classification.massamanArea, `${classification.name}.mdx`)
  const stalePath = path.join(DOCS_REF, classification.massamanArea, `${classification.name}.md`)
  const errors = check
    ? await verifyProxy(classification, transformed, outPath, stalePath)
    : await writeProxy(transformed, outPath, stalePath)

  return {
    entry: {
      ...classification,
      status: 'proxy',
      source: 'es-toolkit',
      upstreamUrl,
      expectedFile: `${refBase(classification)}.mdx`,
    },
    errors,
    wrote: 1,
    handWritten: 0,
    local: 0,
  }
}

async function processUndocumentedExport(
  classification: Extract<Classification, { kind: 'proxy:es-toolkit' }>,
  es: UpstreamPackage
): Promise<ClassificationResult> {
  const undocumentedReason = (es.undocumentedUpstream ?? {})[
    `${classification.upstreamArea}/${classification.name}`
  ]
  if (undocumentedReason === undefined) {
    return {
      entry: null,
      errors: [
        `missing upstream doc: es-toolkit/${classification.upstreamArea}/${classification.name}.md (re-exported as massaman/${classification.massamanArea})`,
      ],
      wrote: 0,
      handWritten: 0,
      local: 0,
    }
  }

  const expectedFile = await existingRef(classification)
  if (expectedFile === null) {
    return {
      entry: null,
      errors: [
        `allowlisted as undocumented upstream but no hand-written page: ${refBase(classification)}`,
      ],
      wrote: 0,
      handWritten: 0,
      local: 0,
    }
  }

  return {
    entry: {
      ...classification,
      status: 'hand-written',
      source: 'es-toolkit',
      undocumentedUpstream: undocumentedReason,
      expectedFile,
    },
    errors: [],
    wrote: 0,
    handWritten: 1,
    local: 0,
  }
}

async function verifyProxy(
  classification: Reference,
  transformed: string,
  outPath: string,
  stalePath: string
): Promise<string[]> {
  const [existing, stale] = await Promise.all([
    fs.readFile(outPath, 'utf8').catch(() => null),
    fs.pathExists(stalePath),
  ])
  return [
    ...(existing === transformed
      ? []
      : [`drift: docs/reference/${classification.massamanArea}/${classification.name}.mdx`]),
    ...(stale ? [`stale proxy: ${refBase(classification)}.md`] : []),
  ]
}

async function writeProxy(
  transformed: string,
  outPath: string,
  stalePath: string
): Promise<string[]> {
  await Promise.all([fs.outputFile(outPath, transformed), fs.remove(stalePath)])
  return []
}

async function ensureUpstream(repo: string, version: string): Promise<string> {
  const dir = path.join(CACHE_DIR, `es-toolkit-${version}`)
  const docsDir = path.join(dir, 'docs', 'reference')
  if (await fs.pathExists(docsDir)) {
    return dir
  }
  await fs.remove(dir)
  await fs.ensureDir(CACHE_DIR)
  console.log(chalk.gray(`  cloning ${repo}@v${version} into node_modules/.cache/docs-sync/`))
  await $`git clone --depth 1 --branch v${version} --filter=blob:none --sparse https://github.com/${repo}.git ${dir}`
  await $`git -C ${dir} sparse-checkout set docs`
  return dir
}

/**
 * Upstream keeps most reference pages under `docs/reference/<area>/`, but newer
 * entrypoints are top-level doc sections with their own `docs/<area>/reference/`
 * tree, and the published URL mirrors the on-disk path. `fp` is the one we
 * currently mirror; the rest are listed so adding them later is a re-export away.
 */
const SECTION_AREAS = new Set(['compat', 'fp', 'server', 'types'])

function upstreamDocSegments(area: string, name: string): string[] {
  return SECTION_AREAS.has(area)
    ? [area, 'reference', `${name}.md`]
    : ['reference', area, `${name}.md`]
}

function upstreamDocUrl(es: UpstreamPackage, area: string, name: string): string {
  return SECTION_AREAS.has(area)
    ? `${es.siteOrigin}/${area}/reference/${name}.html`
    : `${es.siteUrl}/${area}/${name}.html`
}

async function classifyAllExports(): Promise<Classification[]> {
  const entries = (await fs.readdir(SRC_ROOT, { withFileTypes: true })) as Dirent[]
  const areas = entries.filter((entry: Dirent) => entry.isDirectory() && entry.name !== 'types')
  const classifications = await Promise.all(
    areas.map(async (area: Dirent): Promise<Classification[]> => {
      const indexPath = path.join(SRC_ROOT, area.name, 'index.ts')
      if (!(await fs.pathExists(indexPath))) return []
      const content = await fs.readFile(indexPath, 'utf8')
      return parseExports(content).map((definition) =>
        Object.assign({}, definition, { massamanArea: area.name })
      )
    })
  )
  return classifications.flat()
}

/**
 * Parse `export { ... } from '...'` blocks. Skips `export type { ... }` and
 * inline-type names (`type Foo`). Handles `name as alias` (uses the alias).
 */
function parseExports(content: string): ExportDefinition[] {
  const out: ExportDefinition[] = []
  const blockRe = /export\s+(type\s+)?\{([\s\S]*?)\}\s+from\s+['"]([^'"]+)['"]/g
  let m
  while ((m = blockRe.exec(content)) !== null) {
    const isTypeBlock = Boolean(m[1])
    if (isTypeBlock) continue
    const names = m[2]
      .split(',')
      .map((s) => s.trim())
      .filter(Boolean)
      .filter((s) => !/^type\s+/.test(s))
      .map((s) => {
        const asMatch = s.match(/\s+as\s+(\S+)/)
        return asMatch ? asMatch[1].trim() : s
      })
    const src = m[3]
    for (const name of names) {
      if (src.startsWith('./')) {
        out.push({ name, kind: 'local' })
      } else if (src.startsWith('es-toolkit/')) {
        out.push({
          name,
          kind: 'proxy:es-toolkit',
          upstreamArea: src.slice('es-toolkit/'.length),
        })
      } else if (src === 'ts-pattern') {
        out.push({ name, kind: 'proxy:ts-pattern' })
      }
    }
  }
  return out
}

// Sentinel substring used by orphan detection. Must be unique to generated
// proxy pages and remain in the disclosure below.
const CALLOUT_MARKER = '<summary>Source: es-toolkit</summary>'

function injectProxyCallout(content: string, upstreamUrl: string): string {
  const disclosure =
    `<details>\n` +
    `${CALLOUT_MARKER}\n\n` +
    `Re-exported verbatim from [\`es-toolkit\`](${upstreamUrl}). Implementation, edge cases, and performance behavior are owned upstream. This page mirrors the documentation at the pinned version; the linked source is authoritative.\n\n` +
    `</details>\n`
  return `${content.trimEnd()}\n\n${disclosure}`
}

function decorateProxyPage(content: string, name: string, upstreamUrl: string): string {
  const withImport = content.includes("from '@ciderpress/ui/theme'")
    ? content.replace(
        /import \{ ([^}]+) \} from '@ciderpress\/ui\/theme'/u,
        (_match: string, imports: string) =>
          `import { ${['Badge', ...imports.split(',').map((item) => item.trim())]
            .filter((item, index, values) => values.indexOf(item) === index)
            .toSorted()
            .join(', ')} } from '@ciderpress/ui/theme'`
      )
    : content.replace(/^(#\s+\S[^\n]*\n)/mu, `import { Badge } from '@ciderpress/ui/theme'\n\n$1`)
  const withBadge = withImport.replace(
    /^(#\s+\S[^\n]*)$/mu,
    `$1 <Badge color="#c85a3e">es-toolkit</Badge>`
  )
  return rewriteUpstreamCrossRefs(injectProxyCallout(withBadge, upstreamUrl))
}

function withProxyTitle(content: string, name: string): string {
  return content.replace(/^---\r?\n/u, `---\ntitle: ${JSON.stringify(name)}\n`)
}

// Upstream pages reference site-level docs (bundle-size, performance) via
// relative .md paths that exist on es-toolkit.dev but not in our docs tree.
// Rewrite them to absolute URLs so the links resolve.
function rewriteUpstreamCrossRefs(content: string): string {
  return content.replace(
    /\(((?:\.\.\/)+)(bundle-size|performance)\.md(#[^)]*)?\)/g,
    (_match: string, _depth: string, page: string, anchor: string | undefined) =>
      `(https://es-toolkit.dev/${page}.html${anchor ?? ''})`
  )
}

function refBase(c: Reference): string {
  return `docs/reference/${c.massamanArea}/${c.name}`
}

async function existingRef(c: Reference, fallback = false): Promise<string | null> {
  const candidates = [`${refBase(c)}.mdx`, `${refBase(c)}.md`]
  const existing = await Promise.all(
    candidates.map(async (candidate) => [candidate, await fs.pathExists(path.join(ROOT, candidate))])
  )
  const match = existing.find(([, exists]) => exists)?.[0]
  if (match !== undefined) return match
  if (fallback) return `${refBase(c)}.mdx`
  return null
}

async function detectOrphans(manifest: ManifestEntry[], errors: string[]): Promise<void> {
  const expected = new Set(manifest.map((c) => c.expectedFile).filter(Boolean))
  const areas = (await fs.readdir(DOCS_REF).catch(() => [])) as string[]
  const candidates = await Promise.all(
    areas.map(async (area): Promise<string[]> => {
      const areaPath = path.join(DOCS_REF, area)
      const stat = await fs.stat(areaPath).catch(() => null)
      if (!stat?.isDirectory()) return []
      return ((await fs.readdir(areaPath)) as string[])
        .filter(
          (file: string) =>
            (file.endsWith('.md') || file.endsWith('.mdx')) && !file.startsWith('_')
        )
        .map((file: string) => `docs/reference/${area}/${file}`)
        .filter((relativePath: string) => !expected.has(relativePath))
    })
  )
  const orphanChecks = await Promise.all(
    candidates.flat().map(async (relativePath): Promise<string | null> => {
      const content = await fs.readFile(path.join(ROOT, relativePath), 'utf8').catch(() => '')
      if (!content.includes(CALLOUT_MARKER)) return null
      return `orphan proxy page (no matching re-export): ${relativePath}`
    })
  )
  errors.push(...orphanChecks.filter((error): error is string => error !== null))
}

const PLACEHOLDER_MARKERS = [
  'One-sentence description',
  'Worked-example paragraph',
  'type="Type"',
  'realistic, end-to-end example',
]

async function detectPlaceholderPages(errors: string[]): Promise<void> {
  const areas = await fs.readdir(DOCS_REF).catch(() => [])
  const pages = (
    await Promise.all(
      areas.map(async (area: string) => {
        const areaPath = path.join(DOCS_REF, area)
        const stat = await fs.stat(areaPath).catch(() => null)
        if (!stat?.isDirectory()) return []
        return (await fs.readdir(areaPath))
          .filter((file: string) => file.endsWith('.md') || file.endsWith('.mdx'))
          .map((file: string) => path.join(areaPath, file))
      })
    )
  ).flat()

  await Promise.all(
    pages.map(async (page: string) => {
      const content = await fs.readFile(page, 'utf8')
      const marker = PLACEHOLDER_MARKERS.find((candidate) => content.includes(candidate))
      if (marker === undefined) return
      errors.push(`placeholder content (${marker}): ${path.relative(ROOT, page)}`)
    })
  )
}

async function normalizeReferenceDescriptions(errors: string[], check: boolean): Promise<void> {
  const areas = (await fs.readdir(DOCS_REF).catch(() => [])) as string[]
  const pages = (
    await Promise.all(
      areas.map(async (area: string) => {
        const areaPath = path.join(DOCS_REF, area)
        const stat = await fs.stat(areaPath).catch(() => null)
        if (!stat?.isDirectory()) return []
        return (await fs.readdir(areaPath))
          .filter((file: string) => file.endsWith('.md') || file.endsWith('.mdx'))
          .map((file: string) => path.join(areaPath, file))
      })
    )
  ).flat()

  await Promise.all(
    pages.map(async (page: string) => {
      const content = await fs.readFile(page, 'utf8')
      const normalized = withReferenceDescription(content)
      if (content === normalized) return

      if (check) {
        errors.push(`reference description drift: ${path.relative(ROOT, page)}`)
        return
      }
      await fs.writeFile(page, normalized)
    })
  )
}

async function migrateHandWrittenFields(errors: string[], check: boolean): Promise<void> {
  const areas = (await fs.readdir(DOCS_REF).catch(() => [])) as string[]
  const referencePaths = (
    await Promise.all(
      areas.map(async (area: string) => {
        const areaPath = path.join(DOCS_REF, area)
        const stat = await fs.stat(areaPath).catch(() => null)
        if (!stat?.isDirectory()) return []
        const files = await fs.readdir(areaPath)
        return files
          .filter((file: string) => file.endsWith('.md') || file.endsWith('.mdx'))
          .map((file: string) => path.join(areaPath, file))
      })
    )
  ).flat()

  await Promise.all(
    referencePaths.map(async (referencePath: string) => {
      const original = await fs.readFile(referencePath, 'utf8')
      const transformed = transformReferenceFields(original)
      if (!transformed.changed) return
      const mdxPath = referencePath.replace(/\.md$/u, '.mdx')
      const relative = path.relative(ROOT, referencePath)

      if (check) {
        errors.push(`reference field markup drift: ${relative}`)
        return
      }

      await fs.outputFile(mdxPath, transformed.content)
      if (referencePath !== mdxPath) await fs.remove(referencePath)
    })
  )
}
