#!/usr/bin/env zx
/**
 * docs-sync — mirrors per-symbol reference docs from upstream packages into
 * docs/reference/<area>/<name>.md, injecting a "Direct proxy" callout after
 * the H1. Hand-written pages (originals, ts-pattern, prose, concepts) are
 * never touched.
 *
 * Modes:
 *   pnpm docs:sync              # write
 *   pnpm docs:sync:check        # CI — fail on drift, no writes
 *
 * Inputs:
 *   docs/_meta/upstream-versions.json   (pinned tags)
 *   packages/massaman/src/<area>/index.ts (re-export classifications)
 *
 * Outputs:
 *   docs/reference/<area>/<name>.md     (proxy pages)
 *   docs/_meta/proxies.json             (manifest)
 */

import 'zx/globals'

$.verbose = false

const ROOT = path.resolve(__dirname, '..')
const META_PATH = path.join(ROOT, 'docs', '_meta', 'upstream-versions.json')
const MANIFEST_PATH = path.join(ROOT, 'docs', '_meta', 'proxies.json')
const CACHE_DIR = path.join(ROOT, 'node_modules', '.cache', 'docs-sync')
const SRC_ROOT = path.join(ROOT, 'packages', 'massaman', 'src')
const DOCS_REF = path.join(ROOT, 'docs', 'reference')

const CHECK_MODE = process.argv.includes('--check')

async function main() {
  const cfg = await fs.readJson(META_PATH)
  const es = cfg['es-toolkit']
  const tsp = cfg['ts-pattern']

  console.log(
    chalk.cyan(
      `docs-sync ${CHECK_MODE ? '(check)' : ''} — es-toolkit@${es.version}, ts-pattern@${tsp.version}`
    )
  )

  const upstreamDir = await ensureUpstream(es.repo, es.version)

  const classifications = await classifyAllExports()

  const manifest = []
  const errors = []
  const expectedFiles = new Set()
  let wrote = 0
  let proxyHandWritten = 0
  let locals = 0

  for (const c of classifications) {
    if (c.kind === 'local') {
      locals++
      manifest.push({ ...c, status: 'original', expectedFile: relRef(c) })
      continue
    }

    if (c.kind === 'proxy:ts-pattern') {
      proxyHandWritten++
      manifest.push({
        ...c,
        status: 'hand-written',
        source: 'ts-pattern',
        upstreamUrl: tsp.siteUrl,
        expectedFile: relRef(c),
      })
      continue
    }

    // proxy:es-toolkit
    const upstreamMd = path.join(upstreamDir, 'docs', 'reference', c.upstreamArea, `${c.name}.md`)
    if (!(await fs.pathExists(upstreamMd))) {
      errors.push(
        `missing upstream doc: es-toolkit/${c.upstreamArea}/${c.name}.md (re-exported as massaman/${c.massamanArea})`
      )
      continue
    }
    const upstreamUrl = `${es.siteUrl}/${c.upstreamArea}/${c.name}.html`
    const original = await fs.readFile(upstreamMd, 'utf8')
    const mutated = injectProxyCallout(original, upstreamUrl)
    const outPath = path.join(DOCS_REF, c.massamanArea, `${c.name}.md`)
    expectedFiles.add(outPath)

    if (CHECK_MODE) {
      const existing = await fs.readFile(outPath, 'utf8').catch(() => null)
      if (existing !== mutated) {
        errors.push(`drift: docs/reference/${c.massamanArea}/${c.name}.md`)
      }
    } else {
      await fs.outputFile(outPath, mutated)
    }
    wrote++
    manifest.push({
      ...c,
      status: 'proxy',
      source: 'es-toolkit',
      upstreamUrl,
      expectedFile: relRef(c),
    })
  }

  // Orphan detection: proxy .md on disk that no longer maps to a re-export.
  // We can't blanket-flag all .md (originals are hand-written), so we scope to
  // "looks like a proxy" — has the canonical callout marker on line 3.
  await detectOrphans(manifest, errors)

  if (!CHECK_MODE) {
    await fs.outputJson(
      MANIFEST_PATH,
      {
        $comment: 'Generated by scripts/docs-sync.mjs — do not edit by hand.',
        generatedAt: new Date().toISOString(),
        versions: { 'es-toolkit': es.version, 'ts-pattern': tsp.version },
        counts: { proxy: wrote, handWrittenProxy: proxyHandWritten, original: locals },
        pages: manifest.sort((a, b) =>
          `${a.massamanArea}/${a.name}`.localeCompare(`${b.massamanArea}/${b.name}`)
        ),
      },
      { spaces: 2 }
    )
  }

  // Summary
  console.log(
    chalk.green(`  ${CHECK_MODE ? 'verified' : 'wrote'} ${wrote} proxy pages from es-toolkit`)
  )
  console.log(chalk.gray(`  ${proxyHandWritten} ts-pattern pages are hand-written (not generated)`))
  console.log(chalk.gray(`  ${locals} originals expected (hand-written, not touched)`))

  if (errors.length > 0) {
    console.log(chalk.red(`\n✗ ${errors.length} issue(s):`))
    for (const e of errors) console.log(chalk.red(`  - ${e}`))
    process.exit(1)
  }
  console.log(chalk.green('\n✓ ok'))
}

// -----------------------------------------------------------------------------

async function ensureUpstream(repo, version) {
  const dir = path.join(CACHE_DIR, `es-toolkit-${version}`)
  const docsDir = path.join(dir, 'docs', 'reference')
  if (await fs.pathExists(docsDir)) {
    return dir
  }
  await fs.remove(dir)
  await fs.ensureDir(CACHE_DIR)
  console.log(chalk.gray(`  cloning ${repo}@v${version} into node_modules/.cache/docs-sync/`))
  await $`git clone --depth 1 --branch v${version} --filter=blob:none --sparse https://github.com/${repo}.git ${dir}`
  await $`git -C ${dir} sparse-checkout set docs`
  return dir
}

async function classifyAllExports() {
  const out = []
  const entries = await fs.readdir(SRC_ROOT, { withFileTypes: true })
  for (const entry of entries) {
    if (!entry.isDirectory()) continue
    if (entry.name === 'types') continue
    const indexPath = path.join(SRC_ROOT, entry.name, 'index.ts')
    if (!(await fs.pathExists(indexPath))) continue
    const content = await fs.readFile(indexPath, 'utf8')
    const exports = parseExports(content)
    for (const e of exports) {
      out.push({ ...e, massamanArea: entry.name })
    }
  }
  return out
}

/**
 * Parse `export { ... } from '...'` blocks. Skips `export type { ... }` and
 * inline-type names (`type Foo`). Handles `name as alias` (uses the alias).
 */
function parseExports(content) {
  const out = []
  const blockRe = /export\s+(type\s+)?\{([\s\S]*?)\}\s+from\s+['"]([^'"]+)['"]/g
  let m
  while ((m = blockRe.exec(content)) !== null) {
    const isTypeBlock = Boolean(m[1])
    if (isTypeBlock) continue
    const names = m[2]
      .split(',')
      .map((s) => s.trim())
      .filter(Boolean)
      .filter((s) => !/^type\s+/.test(s))
      .map((s) => {
        const asMatch = s.match(/\s+as\s+(\S+)/)
        return asMatch ? asMatch[1].trim() : s
      })
    const src = m[3]
    for (const name of names) {
      if (src.startsWith('./')) {
        out.push({ name, kind: 'local' })
      } else if (src.startsWith('es-toolkit/')) {
        out.push({
          name,
          kind: 'proxy:es-toolkit',
          upstreamArea: src.slice('es-toolkit/'.length),
        })
      } else if (src === 'ts-pattern') {
        out.push({ name, kind: 'proxy:ts-pattern' })
      }
    }
  }
  return out
}

// Sentinel substring used by orphan detection. Must be unique to generated
// proxy pages and remain on the second line of the GFM alert below.
const CALLOUT_MARKER = '> **Direct proxy**'

function injectProxyCallout(content, upstreamUrl) {
  const callout =
    `> [!NOTE]\n` +
    `${CALLOUT_MARKER} — re-exported verbatim from [\`es-toolkit\`](${upstreamUrl}).\n` +
    `> Implementation, edge cases, and performance behavior are owned upstream.\n` +
    `> This page mirrors the upstream documentation at the pinned version; see the linked source for the authoritative copy.\n\n`
  return content.replace(/^(#\s+\S[^\n]*\n)(\s*\n)?/m, (_match, h1, blank) => {
    return `${h1}${blank || '\n'}${callout}`
  })
}

function relRef(c) {
  return `docs/reference/${c.massamanArea}/${c.name}.md`
}

async function detectOrphans(manifest, errors) {
  const expected = new Set(manifest.map((c) => relRef(c)))
  const areas = await fs.readdir(DOCS_REF).catch(() => [])
  for (const area of areas) {
    const areaPath = path.join(DOCS_REF, area)
    const stat = await fs.stat(areaPath).catch(() => null)
    if (!stat?.isDirectory()) continue
    const files = await fs.readdir(areaPath)
    for (const f of files) {
      if (!f.endsWith('.md') || f.startsWith('_')) continue
      const rel = `docs/reference/${area}/${f}`
      if (expected.has(rel)) continue
      // Only flag as orphan if it looks like a proxy page we generated previously.
      const content = await fs.readFile(path.join(areaPath, f), 'utf8').catch(() => '')
      if (content.includes(CALLOUT_MARKER)) {
        errors.push(`orphan proxy page (no matching re-export): ${rel}`)
      }
    }
  }
}

await main()
